### ISSUE TITLE
M2 async-io compilation issues

### ISSUE THREAD

**Issue by PlamenHristov** [cloud-hypervisor/fuse-backend-rs#194]
Hey team, 

I'm trying to compile the project with async-io feature enabled on an M2 (macOS) and am getting the following error 

```
/registry/src/index.crates.io-6f17d22bba15001f/io-uring-0.5.13/src/util.rs:19:42

19   |                 libc::MAP_SHARED | libc::MAP_POPULATE,
     |                                          ^^^^^^^^^^^^ help: a constant with a similar name exists: `MAP_PRIVATE`
     |
    ::: /Users/phristov/.cargo/registry/src/index.crates.io-6f17d22bba15001f/libc-0.2.154/src/unix/bsd/apple/mod.rs:3334:1
     |
3334 | pub const MAP_PRIVATE: ::c_int = 0x0002;
```

`Cargo.toml`

```
[package]
name = "my-project"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
fuse-backend-rs = { version = "0.12.0", features = ["async-io", "fuse-t"] }
futures = "0.3.30"
libc = "0.2.68"
signal-hook = "0.3.17"
async-trait = "0.1.80"
```

`main.rs`

```
use std::io::{Result as StdResult};
use fuse_backend_rs::api::filesystem::{AsyncFileSystem};

#[tokio::main]
async fn main() -> StdResult<()> {
  println!("hello wordl!");

    Ok(())
}
```

Any ideas on the best way to workaround the issue?

**Comment by lu-zero** [comment]
io-uring does not exist in macos sadly :/

**Comment by PlamenHristov** [comment]
@lu-zero , thank you for getting back to me. 

Sure but is there some way to support async on MacOS?

**Comment by lu-zero** [comment]
I hadn't had even time to look at the code, I'm just a bystander that was looking for a fuse implementation as well :)

**Comment by PlamenHristov** [comment]
Since I couldn't find a better implementation I'll be extending this one, thus let me know if you are missing something and I could include it. 

Alternatively, let me know if you'd found a better one that has better support for MacOS.
