### ISSUE TITLE
Support non-privileged Users

### ISSUE THREAD

**Issue by fzgregor** [cloud-hypervisor/fuse-backend-rs#76]
Thank you for providing `fuse-backend-rs`!

I'm currently transitioning from `fuse_mt` to `fuse-backend-rs` and ran into a really annoying issue. `fuse_mt` makes use of `libfuse`, which allows it to mount fuse file systems without being root. This, unfortunately, is not the case for `fuse-backend-rs` (the root part, not depending on `libfuse` is actually great as pure Rust code simplifies compilation a lot).

The secret sauce behind not requiring root permission is a set-uid program called `fusermount` which mounts the fuse FS on behalves of the user.

I have a working prototype of `fuse-backend-rs` using the `fusermount` mechanism for mounting in https://github.com/fzgregor/fuse-backend-rs. Though, it's still very messy, and I wanted to touch base with you before going forward. It entirely replaces the mount system call with `fusermount` at the moment, which might not be great in certain environments... I thought one could check whether the appropriate permissions are available and then use either mechanism.

So, what are your thoughts about this?

The prototype currently requires https://github.com/polachok/passfd/pull/10 to land.

**Comment by jiangliu** [comment]
Sounds interesting, we should support rootless mounting:)

How about making it an option to either directly invoking mount syscall or executing fusemount?

For the passing fd issue, we already have dependency on the vmm-sys-utils crate, which has a similar implementation but without support of rust async io.
https://docs.rs/vmm-sys-util/0.9.0/vmm_sys_util/sock_ctrl_msg/trait.ScmSocket.html

**Comment by fzgregor** [comment]
> How about making it an option to either directly invoking mount syscall or executing fusemount?

Should this be part of (a field of) `FuseSession`? Along the lines of how `readonly` is handled?

> For the passing fd issue, we already have dependency on the vmm-sys-utils crate, which has a similar implementation but without support of rust async io.
> https://docs.rs/vmm-sys-util/0.9.0/vmm_sys_util/sock_ctrl_msg/trait.ScmSocket.html

Thanks! I adapted the code.

**Comment by jiangliu** [comment]
> > How about making it an option to either directly invoking mount syscall or executing fusemount?
> 
> Should this be part of (a field of) `FuseSession`? Along the lines of how `readonly` is handled?

Sounds great:)

> 
> > For the passing fd issue, we already have dependency on the vmm-sys-utils crate, which has a similar implementation but without support of rust async io.
> > https://docs.rs/vmm-sys-util/0.9.0/vmm_sys_util/sock_ctrl_msg/trait.ScmSocket.html
> 
> Thanks! I adapted the code.

**Comment by bergwolf** [comment]
@fzgregor Any updates? It is really useful to call out `fusermount` to run in an unprivileged environment. Actually, libfuse checks for root privilege to determine whether a call to `fusermount` is necessary. I think you can adopt the same behavior.

**Comment by matthiasgoergens** [comment]
I'm working on re-animating @fzgregor's work.  Current work-in-progress is at https://github.com/matthiasgoergens/fuse-backend-rs/pull/1/files

So far I merged into latest master and added some error handling.

I am working on adding some sort of switch to support both old and new behaviour.
